### ISSUE TITLE
Fails with new model

### ISSUE THREAD

**Issue by slarge** [NOAA-EDAB/DecisionSupportTool#5]
I think I might have had the same issue that @seanhardison1 had this afternoon -- everything worked fine except when a new model was run. Validation messages no longer worked. I know SH was going to re here::here() everything to fix it, did this help with newer versions?

**Comment by seanhardison1** [comment]
Validation messages for viewing output? I can't seem to replicate this error on my machine. What were your steps?

**Comment by slarge** [comment]
I cloned the repo and pulled from master, opened ui.r and server.r and clicked "Run App". I created a new scenario "ExampleRun4" that is identical to ExampleRun3 and ran the model. No error messages. When I click over to "View Output" tab, there is an error in the space where the validation message (from server.R line 356). When no model is specified, it says "Please select an existing scenario or create your own.". If I stop the app and restart the R session and restart the app, ExampleRun4 can be found and the figures are displayed.

**Comment by seanhardison1** [comment]
Just pushed a here::here update to master which should solve this
