### ISSUE TITLE
List required packages in readme

### ISSUE THREAD

**Issue by erinann** [NOAA-EDAB/DecisionSupportTool#9]
Thanks for all the work you've done to get this up and running. 

Could you please list the required R packages in the README for the model and for the shiny app? 

Thank you.

**Comment by slarge** [comment]
Thank you for your patience... 

The following *should* get you there: 

library(shinydashboard)
library(htmlwidgets)
library(rhandsontable)
library(rgdal)
library(sp)
library(maps)
library(maptools)
library(grid)
library(gtable)
library(gridExtra)
library(shinyjs)
library(leaflet)
library(imager)
library(shinyEffects)
library(stringr)
library(dplyr)
